const express = require('express');
const router = express.Router();
const PDFDocument = require('pdfkit');
const { Case, Facility, Payer, Procedure, User } = require('../models');
const { authenticateToken } = require('./auth');
const fs = require('fs');
const path = require('path');

router.use(authenticateToken);

/**
 * Generate PDF invoice
 */
router.get('/:caseId/pdf', async (req, res) => {
  try {
    const caseId = req.params.caseId;
    const caseItem = await Case.findByPk(caseId, {
      include: [
        { model: Facility, as: 'facility' },
        { model: Payer, as: 'payer' },
        { model: Procedure, as: 'procedure' },
        { model: User, as: 'user' }
      ]
    });

    if (!caseItem) {
      return res.status(404).json({ error: 'Case not found' });
    }

    if (caseItem.userId !== req.userId) {
      return res.status(403).json({ error: 'Not authorized' });
    }

    if (caseItem.status !== 'Completed') {
      return res.status(400).json({ error: 'Can only generate invoice for completed cases' });
    }

    // Create PDF
    const doc = new PDFDocument({ margin: 50 });
    const filename = `invoice-${caseId}-${Date.now()}.pdf`;
    const filepath = path.join(__dirname, '../temp', filename);

    // Ensure temp directory exists
    const tempDir = path.join(__dirname, '../temp');
    if (!fs.existsSync(tempDir)) {
      fs.mkdirSync(tempDir, { recursive: true });
    }

    // Pipe PDF to file
    doc.pipe(fs.createWriteStream(filepath));

    // Header
    doc.fontSize(20).text('INVOICE', { align: 'center' });
    doc.moveDown();

    // Invoice details
    doc.fontSize(12);
    doc.text(`Invoice Number: ${caseItem.invoiceNumber || 'N/A'}`);
    doc.text(`Date: ${new Date().toLocaleDateString()}`);
    doc.moveDown();

    // Doctor info
    doc.text(`Doctor: ${caseItem.user.phoneNumber}`);
    doc.moveDown();

    // Patient info
    doc.text('Patient Details:', { underline: true });
    doc.text(`Name: ${caseItem.patientName}`);
    doc.text(`In-patient Number: ${caseItem.inpatientNumber || 'N/A'}`);
    doc.text(`Age: ${caseItem.patientAge || 'N/A'}`);
    doc.moveDown();

    // Procedure details
    doc.text('Procedure Details:', { underline: true });
    doc.text(`Date of Procedure: ${new Date(caseItem.dateOfProcedure).toLocaleDateString()}`);
    doc.text(`Facility: ${caseItem.facility?.name || 'N/A'}`);
    doc.text(`Procedure: ${caseItem.procedure?.name || 'N/A'}`);
    doc.moveDown();

    // Payer info
    if (caseItem.payer) {
      doc.text('Payer:', { underline: true });
      doc.text(`Name: ${caseItem.payer.name}`);
      doc.moveDown();
    }

    // Amount
    doc.fontSize(14);
    doc.text(`Amount: KES ${caseItem.amount || '0.00'}`, { align: 'right' });
    doc.moveDown();

    // Payment status
    doc.fontSize(12);
    doc.text(`Payment Status: ${caseItem.paymentStatus || 'Pending'}`);

    // Notes
    if (caseItem.additionalNotes) {
      doc.moveDown();
      doc.text('Notes:', { underline: true });
      doc.text(caseItem.additionalNotes);
    }

    // Footer
    doc.fontSize(10);
    doc.text('Generated by Doc Time', { align: 'center' });

    doc.end();

    // Wait for PDF to be generated
    await new Promise((resolve) => {
      doc.on('end', resolve);
    });

    // Send file
    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename="${filename}"`);
    fs.createReadStream(filepath).pipe(res);

    // Clean up file after sending
    setTimeout(() => {
      fs.unlinkSync(filepath);
    }, 5000);
  } catch (error) {
    console.error('Error generating invoice:', error);
    res.status(500).json({ error: 'Failed to generate invoice' });
  }
});

module.exports = router;

